name: "Assume IAM Role Through Hub Account"
description: "Two-step AssumeRole going through hub account and then target account"

inputs:
  hub_account_role:
    description: The Role ARN for the hub account (step 1)
    required: true
  target_account_role:
    description: The Role ARN for the target account (step 2)
    required: true
  aws_region:
    description: AWS region
    required: false
    default: us-west-2
  session_name:
    description: Optional session name to log in IAM, describing what this workflow is doing
    required: false
    default: GithubAction

runs:
  using: "composite"
  steps:
    - name: Assume Hub Account Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.hub_account_role }}
        role-duration-seconds: 3600
        role-session-name: ${{ inputs.session_name }}

    - name: Assume Target Account Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.target_account_role }}
        role-duration-seconds: 3600
        role-session-name: ${{ inputs.session_name }}
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
