name: copilot apply secrets
description: apply the latest secrets from the sops .yml file
inputs:
  environment:
    description: the environment to apply secrets to
    required: true
  sops_file:
    description: the full path to the sops file to apply
    required: false
  only_if_changed_since:
    description: if given, will git diff the sops file between this ref and HEAD and only apply if it has changed
    required: false

runs:
  using: composite
  steps:
    - name: install SOPS
      uses: mdgreenwald/mozilla-sops-action@v1.2.0
    - name: get file path
      id: file-path
      shell: bash
      run: |
        path=${{ inputs.sops_file || format('secrets-{0}.yml', inputs.environment) }}
        echo path=$path >> $GITHUB_OUTPUT
    - name: check git diff
      id: check-diff
      if: inputs.only_if_changed_since
      shell: bash
      run: |
        if git diff --quiet ${{inputs.only_if_changed_since}} HEAD -- ${{steps.file-path.outputs.path}}; then
          echo secrets file has not changed
          echo unchanged=1 >> $GITHUB_OUTPUT
        else
          echo secrets file has changed
        fi
    - name: apply secrets
      shell: bash
      if: '!steps.check-diff.outputs.unchanged'
      run: |
        outfile=/tmp/secrets-${{inputs.environment}}.yml

        sops --decrypt --output=${outfile} ${{steps.file-path.outputs.path}}
        copilot secret init --overwrite --cli-input-yaml ${outfile}
        rm ${outfile}
