name: copilot apply secrets
description: apply the latest secrets from the sops .yml file
inputs:
  environment:
    description: the environment to apply secrets to
    required: true
  sops_file:
    description: the full path to the sops file to apply
    required: false

runs:
  using: composite
  steps:
    - name: install SOPS
      uses: mdgreenwald/mozilla-sops-action@v1.2.0
    - name: apply secrets
      shell: bash
      run: |
        sops exec-file ${{ inputs.sops_file || format('secrets-{0}.yml', inputs.environment) }}  'copilot secret init --overwrite --cli-input-yaml {}'
