name: copilot auth to env account
description: assume AWS role into copilot env account
inputs:
  environment:
    description: the environment to auth into
    required: true
  aws_region:
    description: AWS region
    required: false
    default: us-west-2
  session_name:
    description: Optional session name to log in IAM, describing what this workflow is doing
    required: false
    default: GithubAction

runs:
  using: composite
  steps:
    - name: Get Env Role ARN
      id: env-role-arn
      shell: bash
      run: |
        ROLE_ARN=$(copilot env show -n "${{inputs.environment}}" --json | jq -r .environment.managerRoleARN)
        echo "::set-output name=role-arn::${ROLE_ARN}"

    - name: Assume Env Account Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ steps.env-role-arn.outputs.role-arn }}
        role-duration-seconds: "3600"
        role-session-name: ${{ inputs.session_name }}
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
        mask-aws-account-id: false
        role-skip-session-tagging: true
