# Cancel a Copilot deploy by cancelling the CF stack update
name: Copilot Cancel Deploy

on:
  workflow_call:
    inputs:
      application:
        description: The Copilot application name
        required: true
        type: string
      environment:
        description: The app environment to deploy to
        required: true
        type: string
      service:
        description: The copilot service to deploy
        required: true
        type: string
      role_to_assume:
        description: The IAM role to assume using the key/secret creds
        required: true
        type: string
      aws_region:
        required: false
        type: string
        default: us-west-2
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  cancel:
    name: Cancel
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup AWS Copilot
        uses: flemzord/setup-aws-copilot@v1.3

      - name: Assume App Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ inputs.role_to_assume }}
          role-duration-seconds: 3600
          role-session-name: GithubActionDeployCancel

      - name: Get Env Role ARN
        id: env-role-arn
        run: |
          ROLE_ARN=$(copilot env show -n "$ENV" --json | jq -r .environment.managerRoleARN)
          echo "::set-output name=role-arn::${ROLE_ARN}"

      - name: Assume Env Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ steps.env-role-arn.outputs.role-arn }}
          role-duration-seconds: 3600
          role-session-name: GithubActionDeployCancel
          role-skip-session-tagging: true

      - name: Cancel Deploy
        env:
          APP: "${{ inputs.application }}"
          ENV: "${{ inputs.environment }}"
          SVC: "${{ inputs.service }}"
        run: |
          STACK="${APP}-${ENV}-${SVC}"
          echo Cancelling CloudFormation stack \'"$STACK"\'

          STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK" | jq -r '.Stacks[0].StackStatus')

          if [[ "$STATUS" == "UPDATE_IN_PROGRESS" ]]; then
              aws cloudformation cancel-update-stack --stack-name "$STACK"
              echo Stack update cancelled, rollback in progress
          else
              echo Cannot cancel deploy, stack is in state \'$STATUS\'
              exit 1
          fi
